-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 08, 2017 at 06:12 PM
-- Server version: 10.1.25-MariaDB
-- PHP Version: 7.1.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `medical_assistant`
--

-- --------------------------------------------------------

--
-- Table structure for table `info`
--



CREATE TABLE `info` (
  `Serial_No` int(11) DEFAULT NULL,
  `Name_Of_Diseases` varchar(50) DEFAULT NULL,
  `Symptoms` varchar(2000) NOT NULL,
  `Medicines` varchar(1000) NOT NULL,
  `Preventions` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `info`
--

INSERT INTO `info` (`Serial_No`, `Name_Of_Diseases`, `Symptoms`, `Medicines`, `Preventions`) VALUES
(1, 'Cholera', 'a) Dangerous fluid loss\r\nb) Vomiting\r\nc) Dehydration', 'a) Rice ORS\r\nb) Intravenous cholera saline (Lactated ringers solution)\r\nc) Tablet Azithromycin -> 1gm single dose ; Child- 10mg/kg or Tablet Ciprofloxacillin -> 1gm single dose ; Child- 20-25mg/kg\r\nd) Vaccination with oral cholera vaccine', 'a) Drink and use safe water expanded\r\nb) Wash your hands often with soap and safe water collapsed\r\nc) Use latrines or bury your feces (poop); do not defecate in any body of water collapsed\r\nd) Cook food well (especially seafood), keep it covered, eat it hot, and peel fruits and vegetables collapsed'),
(2, 'Diarrhoea', 'a) Abdominal cramps\r\nb) Abdominal pains\r\nc) Urgency to go to the toilet\r\nd) Frequent passing of loose, watery faeces\r\ne) Nausea\r\nf) Vomiting', 'a) Rice saline orally\r\nb) Tablet Azithromycin -> 1gm single dose; Child-10mg/kg or Tablet Ciprofloxacillin -> 1gm single dose; Child-20-25mg/kg\r\nc) Tablet Metronidazole -> 3 times daily 5 days', 'a) Access to safe drinking-water\r\nb) Use of improved sanitation\r\nc) Hand washing with soap\r\nd) Good personal and food hygiene\r\ne) Health education about how infections spread\r\nf) Rotavirus vaccination\r\n'),
(3, 'Typhoid', 'a) P0oor appetite\r\nb) Abdominal pain\r\nc) Headaches\r\nd) Generalized aches and pains\r\ne) Fever, often up to 104 F\r\nf) Lethargy (usually only if untreated)\r\ng) Intestinal bleeding or perforation (after two to three weeks of the disease)\r\nh) Diarrhea or constipation', '', 'a) Wash your hands. Frequent hand-washing in hot, soapy water is the best way to control infection\r\nb) Avoid drinking untreated water\r\nc) Avoid raw fruits and vegetables\r\nd) Choose hot foods'),
(4, 'Dysentery', 'a) Watery diarrhea initially that may evolve to contain mucus and blood\r\nb) Loss of appetite\r\nc) Straining during bowel movements, with accompanying rectal pain\r\nd) Abdominal pain; body aches\r\ne) Nausea and vomiting\r\nf) Fever and chills\r\ng) Rapid dehydration and weight loss', '', 'a) Maintain Good Personal Hygiene\r\nb) Always Drink Sterilized Water\r\nc) Practice Proper Sewage Disposal\r\nd) Eat Safe And Eat Right\r\ne) Take Precautions While Travelling\r\nf) Keep Your Community Safe'),
(5, 'Dyspepsia', 'a) Nausea\r\nb) Belching\r\nc) Feeling bloated (very full)', '', 'a) Do not chew with your mouth open, talk while chewing, or eat quickly\r\nb) Chew food completely and eat slowly\r\nc) Drink fluids after meals, rather than during\r\nd) Avoid late-night eating\r\ne) Avoid spicy, greasy foods\r\nf) Quit smoking\r\ng) Avoid alcoholic beverages\r\nh) Avoid caffeine'),
(6, 'Headache', 'a) Dull, aching head pain\r\nb) Sensation of tightness or pressure across your forehead or on the sides and back of your head\r\nc) Tenderness on your scalp, neck and shoulder muscles', '', 'a) Avoid headache triggers. Keeping a headache diary can help you determine what triggers your headaches so that you can avoid the triggers\r\nb) Avoid medication overuse\r\nc) Get enough sleep\r\nd) Don\'t skip meals\r\ne) Exercise regularly\r\nf) Reduce stress\r\ng) Reduce caffeine (could vary from person to person)'),
(7, 'Fever', 'a) Sweating\r\nb) Shivering\r\nc) Headache\r\nd) Muscle aches\r\ne) Loss of appetite\r\nf) Dehydration\r\ng) General weakness', '', 'a) The best way to prevent the spread of infection is to wash the hands frequently and avoid touching the face or mouth as much as possible\r\nb) Keep the home and work environment clean\r\nc) Avoid direct contact with sick people\r\n'),
(8, 'Jaundice', 'a) Yellow tinge to the skin and the whites of the eyes, normally starting at the head and spreading down the body\r\nb) Pruritis (itchiness)\r\nc) Fatigue\r\nd) Abdominal pain - typically indicates a blockage of the bile duct\r\ne) Weight loss\r\nf) Vomiting\r\ng) Fever', '', 'a) Maintain proper hygiene and sanitation\r\nb) Eat fresh and warm food\r\nc) Drink clean water\r\nd) Vaccination'),
(9, 'Hepatitis B', 'a) Abdominal pain\r\nb) Dark urine\r\nc) Fever\r\nd) Joint pain\r\ne) Loss of appetite\r\nf) Nausea and vomiting\r\ng) Weakness and fatigue\r\nh) Yellowing of your skin and the whites of your eyes (jaundice)', '', 'a) Avoid sharing personal items, such as razors or toothbrushes\r\nb) Do not share drug needles or other drug equipment (such as straws for snorting drugs)\r\nc) Clean blood spills with a solution containing 1 part household bleach to 9 parts water'),
(10, 'Hepatitis C', 'a) Feeling very tired\r\nb) Sore muscles\r\nc) Joint pain\r\nd) Fever\r\ne) Nausea or poor appetite\r\nf) Stomach pain\r\ng) Itchy skin\r\nh) Dark urine', '', 'a) Never share needles. Intravenous drug users are at greatest risk of becoming infected with hepatitis C because many share needles\r\nb) Avoid direct exposure to blood or blood products\r\nc) Don\'t share personal care items\r\nd) Choose tattoo and piercing parlors carefully\r\ne) Practice safe sex\r\n'),
(11, 'Liver Disease', 'a) Abdominal pain (located on the right side of the body, beneath the ribs)\r\nb) Abnormal stools\r\nc) Flu-like symptoms (e.g., fatigue, nausea, vomiting, muscle or joint pain, fever)\r\nd) Loss of appetite\r\ne) Swelling of abdomen and/or legs\r\n', '', 'a) Practice healthy habits—do not drink or eat after anyone with hepatitis. Wash your hands often. Do not touch your mouth or eyes with dirty hands. Do not touch others’ blood\r\nb) Maintain a healthy diet—avoid high-fat, acidic foods that can increase the chance for gallstones\r\nc) Practice safe sexual habits—avoid sexual contact or always use protection.\r\nd) Get yearly physicals with laboratory blood tests\r\ne) Limit alcohol consumption\r\nf) Stop smoking or taking drugs\r\ng) Limit over-the-counter pain relievers, vitamin supplements and prescription medications that aggravate the liver\r\nh) Get vaccinated against hepatitis A and B\r\ni) Maintain a healthy weight with light exercise and eating a healthy diet'),
(12, 'AIDS', 'a) Rapid weight loss\r\nb) Recurring fever or profuse night sweats\r\nc) Extreme and unexplained tiredness\r\nd) Prolonged swelling of the lymph glands in the armpits, groin, or neck\r\ne) Diarrhea that lasts for more than a week\r\nf) Sores of the mouth, anus or genitals\r\ng) Pneumonia.', '', 'a) Use a new condom every time you have sex\r\nb) Consider the drug \'Truvada\'\r\nc) Tell your sexual partners if you have HIV\r\nd) Use a clean needle\r\ne) If you\'re pregnant, get medical care right away\r\nf) Consider male circumcision\r\n'),
(13, 'Pneumonia', 'a) Chest pain when you breathe or cough\r\nb) Confusion or changes in mental awareness (in adults age 65 and older)\r\nc) Cough, which may produce phlegm\r\nd) Fatigue\r\nf) Fever, sweating and shaking chills', '', 'a) Get Vaccinated\r\nb) Wash Your Hands\r\nc) Don\'t Smoke\r\nd) Be Aware of Your General Health'),
(14, 'Pertussis', 'a) Mild coughing\r\nb) Sneezing\r\nc) Runny nose\r\nd) Low fever (below 102 F)', '', 'a) Cover your mouth and nose with a tissue when you cough or sneeze\r\nb) Put your used tissue in the waste basket\r\nc) Cough or sneeze into your upper sleeve or elbow, not your hands, if you don\'t have a tissue\r\nd) Wash your hands often with soap and water for at least 20 seconds\r\ne) Use an alcohol-based hand rub if soap and water are not available'),
(15, 'Chicken Pox', 'a) Fever\r\nb) Loss of appetite\r\nc) Headache\r\nd) Tiredness and a general feeling of being unwell (malaise)\r\ne) Appearing rash\r\n', '', 'a) Avoid contact with people at risk\r\nb) Clean and wash regularly\r\nc) Check before travelling on a plane\r\nd) Have Chickenpox vaccination'),
(16, 'Measles', 'a) Fever\r\nb) Dry cough\r\nc) Runny nose\r\nd) Sore throat\r\ne) Inflamed eyes (conjunctivitis)\r\nf) Tiny white spots with bluish-white centers on a red background found inside the mouth on the inner lining of the cheek — also called Koplik\'s spots.\r\n', '', 'a) Wash your hands often\r\nb) If soap and water aren’t available, clean your hands with hand sanitizer (containing at least 60% alcohol)\r\nc) Don’t touch your eyes, nose, or mouth. If you need to touch your face, make sure your hands are clean\r\nd) Cover your mouth and nose with a tissue or your sleeve (not your hands) when coughing or sneezing\r\ne) Try to avoid close contact, such as kissing, hugging, or sharing eating utensils or cups, with people who are sick\r\n'),
(17, 'Pox', 'a) Fever\r\nb) Loss of appetite\r\nc) Headache\r\nd) Tiredness and a general feeling of being unwell (malaise)', '', 'a) Get vaccinated for pox\r\nb) Keep your immune system strong\r\nc) Avoid other children and adults with chickenpox\r\nd) Disinfect your house and hands\r\n'),
(18, 'Age-Related Macular Degeneration', 'a) Visual distortions\r\nb) such as straight lines seeming bent\r\nc) Reduced central vision in one or both eyes', '', 'a) Don\'t smoke\r\nb) Eat plenty of dark, leafy green vegetables, such as raw spinach\r\nc) Take a balanced multivitamin/multimineral supplement, such as Centrum Silver, unless your doctor advises otherwise\r\nd) If you already have AMD, ask your doctor about one of the AREDS formulations or other supplements specially formulated for macular health, such as I-Caps AREDS 2 (Alcon), PreserVision AREDS 2 (Bausch + Lomb), Eyepex Macula (Eyepex Formulas) or MacularProtect Complete AREDS2 (ScienceBased Health)\r\ne) Eat fish or take a fish oil supplement\r\nf) Exercise regularly, and maintain a healthy weight\r\ng) Eat fruit and nuts daily\r\nh) Limit your intake of refined carbohydrates (high-glycemic index foods)\r\ni) Keep your blood pressure and cholesterol under control\r\nj) Wear sunglasses outdoors to block UV and blue light that may cause eye damage\r\nk) Have regular eye exams'),
(19, 'Graves\' Disease', 'a) Anxiety and irritability\r\nb) A fine tremor of your hands or fingers\r\nc) Heat sensitivity and an increase in perspiration or warm, moist skin\r\nd) Weight loss, despite normal eating habits\r\ne) Enlargement of your thyroid gland (goiter)\r\nf) Change in menstrual cycles\r\ng) Erectile dysfunction or reduced libido\r\nh) Frequent bowel movements\r\ni) Bulging eyes (Graves\' ophthalmopathy)\r\nj) Thick, red skin usually on the shins or tops of the feet (Graves\' dermopathy)\r\nk) Rapid or irregular heartbeat (palpitations)', '', 'a) Be aware of a genetic link of Graves disease in your family and take precautions accordingly to lower the risk of developing this condition yourself\r\nb) Avoid mental stress that may aggravate the onset of this disease. Practice yoga and meditation to calm your mind.\r\nc) Avoid cigarette smoking and other toxic habits\r\nd) Avoid the use of steroids, which may in turn lead to the onset of Graves disease\r\ne) Avoid trauma or injury to the thyroid gland'),
(20, 'Cataracts', 'a) Clouded, blurred or dim vision\r\nb) Increasing difficulty with vision at night\r\nc) Sensitivity to light and glare\r\nd) Need for brighter light for reading and other activities\r\ne) Seeing \"halos\" around lights\r\nf) Frequent changes in eyeglass or contact lens prescription\r\ng) Fading or yellowing of colors', '', 'a) See your eye doctor regularly\r\nb) Eat a diet rich in beneficial nutrients\r\nc) Quit smoking -- or better yet, never start\r\nd) Cut back on the cocktails\r\ne) Protect those eyes from the sun\r\nf) Keep your diabetes under control\r\ng) Avoid using \'Corticosteroid\' medications for any length of time\r\n'),
(21, 'Color Blindness', 'a) Difficulty distinguishing between colors\r\nb) Inability to see shades or tones of the same color\r\nc) Rapid eye movement (in rare cases)', '', 'a) To help reduce your chances of getting acquired color blindness, discuss your use of prescribed medicines with your doctor'),
(22, 'Crossed Eyes (Strabismus)', 'a) Inability to read comfortably\r\nb) Fatigue when reading and unstable', '', 'a) There is no known way to prevent Strabismus\r\nb) It is important to evaluate and treat Strabismus as soon as it occurs'),
(23, 'Diabetes', 'a) Urinating often\r\nb) Feeling very thirsty\r\nc) Feeling very hungry - even though you are eating\r\nd) Extreme fatigue\r\ne) Blurry vision\r\nf) Cuts/bruises that are slow to heal\r\ng) Weight loss - even though you are eating more (type 1)\r\nh) Tingling, pain, or numbness in the hands/feet (type 2)', '', 'a) Check your risk of diabetes\r\nb) Manage your weight\r\nc) Exercise regularly\r\nd) Eat a balanced, healthy diet\r\ne) Limit takeaway and processed foods\r\nf) Limit your alcohol intake\r\ng) Quit smoking\r\nh) Control your blood pressure'),
(24, 'Heart Attack', 'a)Discomfort, pressure, heaviness, or pain in the chest, arm, or below the breastbone\r\nb)Discomfort radiating to the back, jaw, throat, or arm\r\nc)Fullness, indigestion, or choking feeling (may feel like heartburn)\r\nd)Sweating, nausea, vomiting, or dizziness\r\ne)Extreme weakness, anxiety, or shortness of breath\r\nf)Rapid or irregular heartbeats\r\n', '', 'a)Choose a healthy eating plan such as foods low in saturated fat, trans fat,sodium,plenty of fruits and vegetables,fiber-rich whole grains, fish ,limit sugar-sweetened beverages and red meat\r\nb)Be physically active\r\nc)Don’t smoke and avoid secondhand smoke\r\nd)Know your family history\r\ne)Tame your stress\r\nf)Watch your weight\r\nh)Have your blood sugar level checked\r\ni)Don’t brush off snoring\r\nj)Learn the warning signs of a heart attack'),
(25, 'Brain Stroke', 'a)Weakness in the arm or leg or both on the same side\r\nb)Weakness in the muscles of the face\r\nc)Difficulty speaking\r\nd)Coordination problems\r\ne)Dizziness\r\nf)Vision problems\r\ng)Sudden headache\r\nh)Loss of consciousness', '', 'a)Lower blood pressure\r\nb)Treat high cholesterol(if have) with proper diet and exercises\r\nc)Control diabetes\r\nd)Stop smoking\r\ne)Eat a low-fat and low-sodium diet rich in fruits, vegetables, and fish\r\nf)Don’t abuse alcohol or drugs\r\ng)Lose weight'),
(27, 'Kidney Stones', 'a)Severe pain in the side and back, below the ribs\r\nb)Pain that radiates to the lower abdomen and groin\r\nc)Pain that comes in waves and fluctuates in intensity\r\nd)Pain on urination\r\ne)Pink, red or brown and cloudy or foul-smelling urine\r\nf)Nausea and vomiting\r\ng)Urinating more often than usual\r\nh)Fever and chills if an infection is present\r\ni)Urinating small amounts', '', 'a)Stay hydrated\r\nb)Eat more calcium-rich foods\r\nc)Eat less sodium\r\nd)Eat fewer oxalate-rich foods\r\ne)Eat less animal protein\r\nf)Avoid vitamin C supplements\r\ng)Explore herbal remedies'),
(28, 'Appendicites', 'a)Pain around the bellybutton\r\nb)Lower right side abdominal pain\r\nc)Loss of appetite\r\nd)Nausea\r\ne)Vomiting\r\nf)Diarrhea\r\ng)Constipation\r\nh)Inability to pass gas\r\ni)Abdominal swelling\r\nj)Low-grade fever\r\nk)A sense that you might feel better after passing stool\r\n', '', 'Unfortunately, you can’t prevent appendicitis.\r\nHowever, some effective lifestyle changes and dietary tactics may help reduce your risk for it such as :\r\n\r\na)A High-Fiber Diet \r\nb)Well-balanced diet with probiotics\r\nc)Managing your stress levels and getting enough exercise. \r\nd)Taking supplements such as beta-carotene, vitamin C and zinc.'),
(29, 'Parkinson\'s Disease', 'a)Tremor/Shaking\r\nb)Slowed movement \r\nc)Rigid muscles\r\nd)Impaired posture and balance\r\ne)Loss of automatic movements\r\nf)Speech changes\r\ng)Writing changes', '', 'a)Eat Fresh, Raw Vegetables\r\nb)Avoid Pesticides and Petrochemical Solvents\r\nc)Avoid Excess Iron\r\nd)Avoid Excess Manganese\r\ne)Consume sufficient Caffeine\r\nf)Adequate sleep/rest\r\ng)Prevent head injuries\r\nh)Ample Exercise'),
(30, 'Tonsilitis', 'a)A very sore throat\r\nb)Difficulty swallowing or painful swallowing\r\nc)A scratchy-sounding voice\r\nd)Bad breath\r\ne)Fever\r\nf)Chills\r\ng)Earaches\r\nh)Stomachaches\r\ni)Headaches\r\nj)A stiff neck\r\nk)Jaw and neck tenderness due to swollen lymph nodes\r\nl)Tonsils that appear red and swollen\r\nm)Tonsils that have white or yellow spots', '', 'a)Avoid close contact with the person suffering from Tonsillitis\r\nb)Ask the sick person to wash their hands thoroughly and regularly; especially after using the toilet\r\nc)Do not share a toothbrush or other personal items with the person suffering from Tonsillitis\r\nd)Avoid sharing utensils, water bottles, glasses and food with the sick person till they are cured\r\ne)Regularly wash and disinfect the surface and things which a suffering person comes in contact with\r\nf)Ask the sick person to cover their moth with hands or a tissue while sneezing\r\ng)Avoid smoking'),
(31, 'Migraine ', 'a)Throbbing, pulsating pain\r\nb)Light sensitivity\r\nc)Sound sensitivity\r\nd)Nausea\r\ne)Pain on one side\r\nf)Vision changes, blurred vision\r\ng)Aura(flickering lights, spots, or lines)\r\nh)Vomiting\r\ni)Depression, irritability, or excitement', '', 'a)Track Your Triggers\r\nb)Treat Your Allergies\r\nc)Get Electrified\r\nd)Stash Painkillers\r\ne)Spit Out The Gum\r\nf)Go Prophylactic\r\ng)Break The Fast Every Day\r\nh)Watch For Bolts\r\ni)Count Your Omegas'),
(32, 'Insomnia', 'a)Fatigue\r\nb)Problems with attention, concentration or memory (cognitive impairment)\r\nc)Poor performance at school or work\r\nd)Moodiness or irritability\r\ne)Daytime sleepiness\r\nf)Impulsiveness or aggression\r\ng)Lack of energy or motivation\r\nh)Errors or accidents\r\ni)Concern or frustration about your sleep', '', 'a)Stick to a regular bedtime routine\r\nb)Eat well to sleep well\r\nc)Cut the caffeine\r\nd)Say yes to yoga\r\ne)Pop some natural supplements\r\nf)Put down the electronic gadgets\r\ng)Embrace exercise\r\nh)Stop smoking'),
(33, 'Dengue Fever', 'a)Sudden, high fever (up to 106 degrees Fahrenheit)\r\nb)Severe headache\r\nc)Swollen lymph glands\r\nd)Severe joint and muscle pains\r\ne)Skin rash (appearing between two and five days after the initial fever)\r\nf)Mild to severe nausea\r\ng)Mild to severe vomiting\r\nh)Mild bleeding from the nose or gums\r\ni)Mild bruising on the skin\r\nj)Pain behind the eyes', '', 'a)Stay in air-conditioned or well-screened housing\r\nb)Wear protective clothing and treat clothes with repellents like \'permethrin\'\r\nc)Use EPA-registered mosquito repellent\r\nd)Reduce mosquito habitat'),
(34, 'Mumps', 'a)Swollen, painful salivary glands on one or both sides of your face (parotitis)\r\nb)Fever\r\nc)Headache\r\nd)Muscle aches\r\ne)Weakness and fatigue\r\nf)Loss of appetite\r\ng)Pain while chewing or swallowing', '', 'a)Wash hands well and often with soap\r\nb)Don\'t share eating utensils or beverage containers\r\nc)Surfaces that are frequently touched should also be regularly cleaned with cleaning wipes\r\nd)Limit your contact with people who have known mumps symptoms.\r\ne)Get Vaccinated'),
(35, 'Tuberculosis', 'a)Coughing that lasts three or more weeks\r\nb)Coughing up blood\r\nc)Chest pain, or pain with breathing or coughing\r\nd)Unintentional weight loss\r\ne)Fatigue\r\nf)Fever\r\ng)Night sweats\r\nh)Chills\r\ni)Loss of appetite', '', 'a)Improving the ventilation in indoor spaces so there are fewer bacteria in the air\r\nb)Using germicidal ultraviolet lamps to kill airborne bacteria in buildings \r\nwhere people at high risk of tuberculosis live or congregate\r\nc)Treating latent infection before it becomes active\r\nd)Taking Tuberculosis Vaccine'),
(36, 'Piles', 'a)A hard lump may be felt around the anus. It consists of coagulated blood,this can be painful\r\nb)After going to the toilet, a feeling that the bowels are still full\r\nc)Bright red blood after a bowel movement\r\nd)Itchiness around the anus\r\ne)Mucus discharge when emptying the bowels\r\nf)Pain while defecating\r\ng)The area around the anus may be red and sore.', '', 'a)Do not delay bowel movements\r\nb)Use wipes over toilet paper\r\nc)Avoid taking too long in the bathroom\r\nd)Keep the anal area clean\r\ne)Stay hydrated\r\nf)Add more fiber to your diet\r\ng)Exercise regularly\r\nh)Lose weight if necessary'),
(37, 'Chikungunya', 'a)Most people infected with chikungunya virus will develop some symptoms\r\nb)Symptoms usually begin 3–7 days after being bitten by an infected mosquito\r\nc)The most common symptoms are fever and joint pain\r\nd)Other symptoms may include headache, muscle pain, joint swelling, or rash\r\ne)Chikungunya disease does not often result in death, but the symptoms can be severe and disabling', '', 'a)Use air conditioning or window/door screens to keep mosquitoes outside. If you are not able to protect yourself from mosquitoes inside your home or hotel,sleep under a mosquito bed net\r\nb)Help reduce the number of mosquitoes outside your home or hotel room by emptying standing water from containers such as flowerpots or buckets\r\nc)When weather permits, wear long-sleeved shirts and long pants\r\nd)Use insect repellents'),
(38, 'Malaria', 'a)Shaking chills that can range from moderate to severe\r\nb)High fever\r\nc)Profuse sweating\r\nd)Headache\r\ne)Nausea\r\nf)Vomiting\r\ng)Diarrhea\r\nh)Anemia\r\ni)Muscle pain\r\nj)Convulsions\r\nk)Bloody stools', '', 'a)Use air conditioning or window/door screens to keep mosquitoes outside. If you are not able to protect yourself from mosquitoes inside your home or hotel,\r\nsleep under a mosquito bed net.\r\nb)Help reduce the number of mosquitoes outside your home or hotel room by emptying standing water from containers such as flowerpots or buckets.\r\nc)When weather permits, wear long-sleeved shirts and long pants.\r\nd)Use insect repellents\r\n'),
(39, 'Bird Flu', 'a)Cough\r\nb)Diarrhea\r\nc)Respiratory difficulties\r\nd)Fever (over 100.4°F or 38°C)\r\ne)Headache\r\nf)Muscle aches\r\ng)Malaise\r\nh)Runny nose\r\ni)Sore throat', '', 'a)Wash your hands regularly, particularly before and after handling food\r\nb)Turn away from other people and cover your mouth with tissues when you cough or sneeze\r\nc)Dispose of tissues immediately after use and wash your hands with soap and warm water\r\nd)Avoid public places if you\'re ill \r\ne)Make sure you maintain a good level of general health and have any recommended vaccinations, such as the pneumococcal vaccination and seasonal flu vaccine,\r\nif you\'re in a high-risk group – for example, if you have a long-term illness such as asthma or you\'re 65 or over'),
(40, 'Anthrax', 'a)A group of small blisters or bumps that may itch\r\nb)Swelling can occur around the sore\r\nc)A painless skin sore (ulcer) with a black center that appears after the small blisters or bumps\r\nd)Most often the sore will be on the face, neck, arms, or hands', '', 'a)Do not eat meat that has not been properly slaughtered and cooked\r\nb)Do not work with raw animal hides, fur or skin, especially those of goats, sheep, or cows\r\n'),
(41, 'Polio', 'a)Fever\r\nb)Sore throat\r\nc)Headache\r\nd)Vomiting\r\ne)Fatigue\r\nf)Back pain or stiffness\r\ng)Neck pain or stiffness\r\nh)Pain or stiffness in the arms or legs\r\ni)Muscle weakness or tenderness\r\nj)Meningitis', '', 'a)Polio can be prevented through immunization. Polio vaccine, given multiple times, almost always protects a child for life\r\n'),
(42, 'Diptheria', 'a)A thick, gray membrane covering your throat and tonsils\r\nb)A sore throat and hoarseness\r\nc)Swollen glands (enlarged lymph nodes) in your neck\r\nd)Difficulty breathing or rapid breathing\r\ne)Nasal discharge\r\nf)Fever and chills\r\ng)Malaise', '', 'a)The best way to prevent diphtheria is to get vaccinated. \r\nb)Hygenic lifestyle\r\n'),
(43, 'Tetanus ', 'a)Stiffness of the neck, jaw, and other muscles, often accompanied by a grotesque, grinning expression\r\nb)Difficulty swallowing\r\nc)Irritability\r\nd)Uncontrollable spasms of the jaw, called lockjaw, and neck muscles\r\ne)Painful, involuntary contraction of other muscles', '', 'a)Get vaccinated. \r\nb)Hygienic Lifestyle'),
(44, 'Asthma', 'a)Shortness of breath\r\nb)Chest tightness or pain\r\nc)Trouble sleeping caused by shortness of breath, coughing or wheezing\r\nd)A whistling or wheezing sound when exhaling (wheezing is a common sign of asthma in children)\r\ne)Coughing or wheezing attacks that are worsened by a respiratory virus, such as a cold or the flu', '', 'a)Get vaccinated for influenza and pneumonia\r\nb)Fully take part in exercise and sports\r\nc)Sleep all night\r\nd)Attend school or work regularly\r\ne)Have the clearest lungs possible\r\nf)Have no emergency visits or stays in the hospital'),
(44, 'Ebola', 'a)Fever\r\nb)Severe headache\r\nc)Joint and muscle aches\r\nd)Chills\r\ne)Weakness', '', 'a)There’s no vaccine to prevent Ebola. The best way to avoid catching the disease is by not traveling to areas where the virus is found\r\nb)Health care workers can prevent infection by wearing masks, gloves, and goggles whenever they come into contact with people who may have Ebola\r\n'),
(45, 'Arthitis', 'a)Fatigue\r\nb)Joint pain\r\nc)Joint tenderness\r\nd)Joint swelling\r\ne)Joint redness\r\nf)Joint warmth\r\ng)Joint stiffness\r\nh)Loss of joint range of motion\r\ni)Many joints affected (polyarthritis)\r\nj)Limping\r\nk)Joint deformity\r\nl)Both sides of the body affected(symmetric)\r\nm)Loss of joint function\r\nn)Anemia\r\no)Fever', '', 'a)Eat Fish\r\nb)Control Your Weight\r\nc)Exercise\r\nd)Avoid Injury\r\ne)Protect Your Joints'),
(46, 'Bronchitis', 'a)Cough\r\nb)Production of mucus (sputum), which can be clear, white, yellowish-gray or green in color — rarely, it may be streaked with blood\r\nc)Fatigue\r\nd)Shortness of breath\r\ne)Slight fever and chills\r\nf)Chest discomfort', '', 'a)Do not start smoking; quit smoking if you already smoke\r\nb)Avoid lung irritants such as smoke, dust, fumes, vapors, and air pollution If avoiding exposure is not possible, wear a mask that covers the nose and mouth\r\nc)Wash hands often to limit exposure to germs and bacteria\r\nd)Get a yearly flu vaccine\r\ne)Get a pneumonia vaccine'),
(47, 'Ear Infection(Ottitis Media)', 'a)Mild pain or discomfort inside the ear\r\nb)A feeling of pressure inside the ear that persists\r\nc)Fussiness in young infants\r\nd)Pus-like ear drainage\r\ne)Hearing loss', '', 'a)Create smoke-free environment\r\nb)Minimal Usage of pacifiers\r\nc)Get pneumococcal vaccination\r\nd)Get flu vaccinations\r\ne)Have \'xylitol\' gum\r\nf)Dietary supplements of zinc\r\ng)Tonsil surgery and the use of ear tubes'),
(48, 'Influenza', 'a)Fever or feeling feverish/chills\r\nb)Cough\r\nc)Sore throat\r\nd)Runny or stuffy nose\r\ne)Muscle or body aches\r\nf)Headaches\r\ng)Fatigue (tiredness)\r\nh)Some people may have vomiting and diarrhea, though this is more common in children than adults.\r\n', '', 'a)Don\'t smoke.\r\nb)Wash your hands often. \r\nc)Breast-feeding infants for the first year of life\r\nd)Practicing good hygiene, including washing hands regularly\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `info2`
--

CREATE TABLE `info2` (
  `Serial_No` int(11) NOT NULL,
  `Name_Of_Diseases` varchar(50) NOT NULL,
  `Symptoms` varchar(2000) NOT NULL,
  `Medicines` varchar(1000) NOT NULL,
  `Preventions` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `info2`
--

INSERT INTO `info2` (`Serial_No`, `Name_Of_Diseases`, `Symptoms`, `Medicines`, `Preventions`) VALUES
(1, 'Cholera', '1.Dangerous fluid loss\r\n2.Vomiting\r\n3.Dehydration\r\n', '1.Rice ORS.\r\n2.Intravenous cholera saline (Lactated ringers solution).\r\n3.Tablet Azithromycin -> 1gm single dose; Child- 10mg/kg\r\nor Tablet Ciprofloxacillin -> 1gm single dose; Child- 20-25mg/kg.\r\n4.Vaccination with oral cholera vaccine.', '1.Drink and use safe water expanded.\r\n2.Wash your hands often with soap and safe water collapsed.\r\n3.Use latrines or bury your feces (poop); do not defecate in any body of water collapsed.\r\n4.Cook food well (especially seafood), keep it covered, eat it hot, and peel fruits and vegetables collapsed.'),
(2, 'Diarrhoea', '1.Abdominal cramps.\r\n2.Abdominal pains.\r\n3.Urgency to go to the toilet.\r\n4.Frequent passing of loose, watery faces.\r\n5.Nausea.\r\n6.Vomiting.', '1.Rice saline orally.\r\n2.Tablet Azithromycin -> 1gm single dose; Child- 10mg/kg\r\nor Tablet Ciprofloxacillin -> 1gm single dose; Child-20-25mg/kg\r\n3.Tablet Metronidazole -> 3 times daily 5 days.\r\n', '1.Access to safe drinking-water.\r\n2.Use of improved sanitation.\r\n3.Hand washing with soap.\r\n4.Good personal and food hygiene.\r\n5.Health education about how infections spread.\r\n6.Rotavirus vaccination.'),
(3, 'Typhoid', '1.Poor appetite.\r\n2.Abdominal pain.\r\n3.Headaches.\r\n4.Generalized aches and pains.\r\n5.Fever, often up to 104 F.\r\n6.Lethargy (usually only if untreated).\r\n7.Intestinal bleeding or perforation (after two to three weeks of the disease).\r\n8.Diarrhea or constipation.', '1.Paracetamol -> one tablet 6 hourly if temp>100 degree F.\r\n2.Injection Ceftriaxone 100mg/kg/day for 7-10 days\r\nor Ciprofloxacin 25mg/kg/day for 10 days\r\nor Cefuroxime/Cefixime 20mg/kg/day for 10 days\r\nor Azithromycin 20mg/kg/day for 10 days.\r\n3.Diclofenac suppository 50 mg per rectally if temp>103 degree F.\r\n4.Vaccination with typhoid vaccine.', '1.Wash your hands. Frequent hand-washing in hot, soapy water is the best way to control infection.\r\n2.Avoid drinking untreated water.\r\n3.Avoid raw fruits and vegetables.\r\n4.Choose hot foods.'),
(4, 'Dysentery', '1.Watery diarrhea initially that may evolve to contain mucus and blood.\r\n2.Loss of appetite.\r\n3.Straining during bowel movements, with accompanying rectal pain.\r\n4.Abdominal pain; body aches.\r\n5.Nausea and vomiting.\r\n6.Fever and chills.\r\n7.Rapid dehydration and weight loss.', '1.Tablet Pivmecillinam 200mg -> one tablet six hourly for 5 days\r\nOr Tablet Nitazoxanide 500mg -> one tablet 12 hourly for 5 days\r\nOr Nalidixic acid 500mg -> one tablet 8 hourly for 5 days.', '1.Maintain Good Personal Hygiene.\r\n2.Always Drink Sterilized Water.\r\n3.Practice Proper Sewage Disposal.\r\n4.Eat Safe And Eat Right.\r\n5.Take Precautions While Travelling.\r\n6.Keep Your Community Safe.'),
(5, 'Dyspepsia', '1.Nausea.\r\n2.Belching.\r\n3.Feeling bloated (very full).', '1.Tablet Domperidone 10mg -> one tablet 8 hourly half an hour befoe meal.\r\n2.Esomeprazole 20mg -> one tablet 12 hourly half an hour before meal.\r\n3.Magaldrate + Simethicone suspension -> 2-4 teaspoonful orally 3-4 times daily after 20-60 minutes of meals & at bedtime.   ', '1.Do not chew with your mouth open, talk while chewing, or eat quickly.\r\n2.Chew food completely and eat slowly.\r\n3.Drink fluids after meals, rather than during.\r\n4.Avoid late-night eating.\r\n5.Avoid spicy, greasy foods.\r\n6.Quit smoking.\r\n7.Avoid alcoholic beverages.\r\n8.Avoid caffeine.'),
(6, 'Headache', '1.Dull, aching head pain.\r\n2.Sensation of tightness or pressure across your forehead or on the sides and back of your head.\r\n3.Tenderness on your scalp, neck and shoulder muscles.\r\n', '1.Tablet Paracetamol 500mg -> two tablets 8 hourly daily; \r\nMaximum dose: 8 tablets daily;\r\nChild: 15-20mg/kg/day six hourly or\r\nTablet Paracetamol plus Caffeine -> one tablet 4-6 hourly daily; \r\nMaximum dose 8 tablets daily.\r\n2.Tablet Pizotifen 0.5mg -> one tablet 8 hourly daily.\r\n3.Tablet Fluphenazine hydrochloride + Nortriptyline -> 1 tablet 2 to 3 times daily.\r\n', '1.Avoid headache triggers; keeping a headache diary can help you determine what triggers your headaches so that you can avoid the triggers.\r\n2.Avoid medication overuse.\r\n3.Get enough sleep.\r\n4.Don\'t skip meals.\r\n5.Exercise regularly.\r\n6.Reduce stress.\r\n7.Reduce caffeine.'),
(7, 'Jaundice', '1.Yellow tinge to the skin and the whites of the eyes, normally starting at the head and spreading down the body.\r\n2.Pruritis (itchiness).\r\n3.Fatigue.\r\n4.Abdominal pain - typically indicates a blockage of the bile duct.\r\n5.Weight loss.\r\n6.Vomiting.\r\n7.Fever.', '1.Complete bed rest.\r\n2.Plenty of fluid orally. \r\n3.Dextrose 10% IV.\r\n4.Low fat protein diet.\r\n5.Tablet Ondansetron 8mg -> one tablet 8 hourly half an hour before meal if nausea & vomiting.\r\n6.Tablet multivitamins -> one tablet 12 hourly for two months.', '1.Maintain proper hygiene and sanitation.\r\n2.Eat fresh and warm food.\r\n3.Drink clean water.\r\n4.Vaccination.\r\n'),
(8, 'Hepatitis B', '1.Abdominal pain.\r\n2.Dark urine.\r\n3.Fever.\r\n4.Joint pain.\r\n5.Loss of appetite.\r\n6.Nausea and vomiting.\r\n7.Weakness and fatigue.\r\n8.Yellowing of your skin and the whites of your eyes (jaundice).\r\n', '1.Complete bed rest.\r\n2.Plenty of fluid orally. \r\n3.Low fat protein diet.\r\n4.Tablet Ondansetron 8mg -> one tablet 8 hourly half an hour before meal if nausea & vomiting.\r\n5.Tablet multivitamins -> one tablet 12 hourly for two months.\r\n6.Vaccination with Hepatitis B vaccine.', '1.Avoid sharing personal items, such as razors or toothbrushes.\r\n2.DO NOT share drug needles or other drug equipment (such as straws for snorting drugs).\r\n3.Clean blood spills with a solution containing 1 part household bleach to 9 parts water.'),
(9, 'Hepatitis C', '1.Feeling very tired.\r\n2.Sore muscles.\r\n3.Joint pain.\r\n4.Fever.\r\n5.Nausea or poor appetite.\r\n6.Stomach pain.\r\n7.Itchy skin.\r\n8.Dark urine.\r\n', '1.Hospitalization. \r\n2.Symptomatic management. ', '1.Never share needles. Intravenous drug users are at greatest risk of becoming infected with hepatitis C because many share needles.\r\n2.Avoid direct exposure to blood or blood products.\r\n3.Don\'t share personal care items.\r\n4.Choose tattoo and piercing parlors carefully.\r\n5.Practice safe sex.'),
(10, 'Liver Disease', '1.Abdominal pain (located on the right side of the body, beneath the ribs)\r\n2.Abnormal stools.\r\n3.Flu-like symptoms (e.g., fatigue, nausea, vomiting, muscle or joint pain, fever).\r\n4.Loss of appetite.\r\n5.Swelling of abdomen and/or legs.\r\n', '1.Hospitalization. \r\n2.Symptomatic management. ', '1.Practice healthy habits—do not drink or eat after anyone with hepatitis, wash your hands often, do not touch your mouth or eyes with dirty hands, do not touch others’ blood.\r\n2.Maintain a healthy diet—avoid high-fat, acidic foods that can increase the chance for gallstones.\r\n3.Practice safe sexual habits—avoid sexual contact or always use protection.\r\n4.Get yearly physicals with laboratory blood tests.\r\n5.Limit alcohol consumption.\r\n6.Stop smoking or taking drugs.\r\n7.Limit over-the-counter pain relievers, vitamin supplements and prescription medications that aggravate the liver.\r\n8.Get vaccinated against hepatitis A and B.\r\n9.Maintain a healthy weight with light exercise and eating a healthy diet.'),
(11, 'AIDS', '1.Rapid weight loss.\r\n2.Recurring fever or profuse night sweats.\r\n3.Extreme and unexplained tiredness.\r\n4.Prolonged swelling of the lymph glands in the armpits, groin, or neck.\r\n5.Diarrhea that lasts for more than a week.\r\n6.Sores of the mouth, anus, or genitals.\r\n7.Pneumonia.', '1.Hospitalization.\r\n2.Symptomatic management. ', '1.Use a new condom every time you have sex.\r\n2.Consider the drug Truvada.\r\n3.Tell your sexual partners if you have HIV.\r\n4.Use a clean needle.\r\n5.If you\'re pregnant, get medical care right away.\r\n6.Consider male circumcision.'),
(12, 'Pneumonia', '1.Chest pain when you breathe or cough.\r\n2.Confusion or changes in mental awareness (in adults age 65 and older).\r\n3.Cough, which may produce phlegm.\r\n4.Fatigue.\r\n5.Fever, sweating and shaking chills.', '1.Hospitalization.\r\n2.Nebulization with salbutamol solution & normal saline.\r\n3.Injection Ceftriaxone 100mg/kg/day for 7/10 days.\r\n', '1.Get Vaccinated.\r\n2.Wash Your Hands.\r\n3.Don\'t Smoke.\r\n4.Be Aware of Your General Health.\r\n'),
(13, 'Pertussis', '1.Mild coughing.\r\n2.Sneezing.\r\n3.Runny nose.\r\n4.Low fever (below 102 F).', '1.Complete isolated bedrest.\r\n2.Tablet Erythromycin 500mg -> one tablet 6 hourly daily for 10 days.\r\n3.Vaccination with DPT vaccine/', '1.Cover your mouth and nose with a tissue when you cough or sneeze.\r\n2.Put your used tissue in the waste basket.\r\n3.Cough or sneeze into your upper sleeve or elbow, not your hands, if you don\'t have a tissue.\r\n4.Wash your hands often with soap and water for at least 20 seconds.\r\n5.Use an alcohol-based hand rub if soap and water are not available.\r\n\r\n\r\n'),
(14, 'Chicken Pox', '1.Fever.\r\n2.Loss of appetite.\r\n3.Headache.\r\n4.Tiredness and a general feeling of being unwell (malaise).\r\n5.appearing rash.', '1.Complete isolated bedrest.\r\n2.Acyclovir 200mg -> one tablet 5 times daily for 5-10 days.\r\n3.Paracetamol 500mg -> 2 tablets 8 hourly if fever & pain.\r\n4.Cetirizine 10mg/Diphenhydramine hydrochloride/Loratadine -> one tablet at night if itching.\r\n5.Use Calamine 15% + Zinc oxide 5% over skin if severe itching. \r\n6.Vaccination with Varicella virus vaccine.\r\n', '1.Avoid contact with people at risk.\r\n2.Clean and wash regularly.\r\n3.Check before travelling on a plane.\r\n4.Chickenpox vaccination.'),
(15, 'Measles', '1.Fever.\r\n2.Dry cough.\r\n3.Runny nose.\r\n4.Sore throat.\r\n5.Inflamed eyes (conjunctivitis).\r\n6.Tiny white spots with bluish-white centers on a red background found inside the mouth on the inner lining of the cheek — also called Koplik\'s spots.\r\n', '1.Symptomatic management: \r\nFor fever- paracetamol 500mg -> 1-2 tablets 4-6 hourly daily; \r\nFor itching- Cetirizine 10mg -> 1 tablet daily at bedtime. \r\n2.Complete isolated bed rest.\r\n3.Vaccination with MMR vaccine or measles vaccine.', '1.Wash your hands often.\r\n2.If soap and water aren’t available, clean your hands with hand sanitizer (containing at least 60% alcohol).\r\n3.Don’t touch your eyes, nose, or mouth. If you need to touch your face, make sure your hands are clean.\r\n4.Cover your mouth and nose with a tissue or your sleeve (not your hands) when coughing or sneezing.\r\n5.Try to avoid close contact, such as kissing, hugging, or sharing eating utensils or cups, with people who are sick.'),
(16, 'Pox', '1.Fever.\r\n2.Loss of appetite.\r\n3.Headache.\r\n4.Tiredness and a general feeling of being unwell (malaise).', '', '1.Get vaccinated for pox.\r\n2.Keep your immune system strong.\r\n3.Avoid other children and adults with chickenpox.\r\n4.Disinfect your house and hands.'),
(17, 'Age-Related Macular Degeneration', '1.Visual distortions.\r\n2.Such as straight lines seeming bent.\r\n3.Reduced central vision in one or both eyes.', '1.Tablet Vitamin E (200mg) -> 200-400mg daily. \r\n2.Verteporfin (15mg) injection.\r\n3.Ranibizumab (10mg) injection.\r\n', '1.Don\'t smoke.\r\n2.Eat plenty of dark, leafy green vegetables, such as raw spinach.\r\n3.Take a balanced multivitamin/multimineral supplement, such as Centrum Silver, unless your doctor advises otherwise.\r\n4.If you already have AMD, ask your doctor about one of the AREDS formulations or other supplements specially formulated for macular health, such as I-Caps AREDS 2 (Alcon), PreserVision AREDS 2 (Bausch + Lomb), Eyepex Macula (Eyepex Formulas) or MacularProtect Complete AREDS2 (ScienceBased Health).\r\n5.Eat fish or take a fish oil supplement.\r\n6.Exercise regularly, and maintain a healthy weight.\r\n7.Eat fruit and nuts daily.\r\n8.Limit your intake of refined carbohydrates (high-glycemic index foods).\r\n9.Keep your blood pressure and cholesterol under control.\r\n10.Wear sunglasses outdoors to block UV and blue light that may cause eye damage.\r\n11.Have regular eye exams.\r\n'),
(18, 'Graves\' Disease', '1.Anxiety and irritability.\r\n2.A fine tremor of your hands or fingers.\r\n3.Heat sensitivity and an increase in perspiration or warm, moist skin.\r\n4.Weight loss, despite normal eating habits.\r\n5.Enlargement of your thyroid gland (goiter).\r\n6.Change in menstrual cycles.\r\n7.Erectile dysfunction or reduced libido\r\n8.Frequent bowel movements.\r\n9.Bulging eyes (Graves\' ophthalmopathy).\r\n10.Thick, red skin usually on the shins or tops of the feet (Graves\' dermopathy).\r\n11.Rapid or irregular heartbeat (palpitations).', '1.Tablet Carbimazole (5mg) -> initially 20-60mg daily as divided dose, reduced gradually once euthyroidism is achieved;\r\nmaintenance dose: 5-15mg daily for at least 1 year or 18 month.\r\n2.Iodine (potassium iodide).\r\n3.Tablet Propranolol hydrochloride (10mg) -> 10-40mg, 3-4 times daily.', '1.Be aware of a genetic link of Graves disease in your family and take precautions accordingly to lower the risk of developing this condition yourself.\r\n2.Avoid mental stress that may aggravate the onset of this disease; practice yoga and meditation to calm your mind.\r\n3.Avoid cigarette smoking and other toxic habits.\r\n4.Avoid the use of steroids, which may in turn lead to the onset of Graves disease.\r\n5.Avoid trauma or injury to the thyroid gland.'),
(19, 'Cataracts', '1.Clouded, blurred or dim vision.\r\n2.Increasing difficulty with vision at night.\r\n3.Sensitivity to light and glare.\r\n4.Need for brighter light for reading and other activities.\r\n5.Seeing \"halos\" around lights.\r\n6.Frequent changes in eyeglass or contact lens prescription.\r\n7.Fading or yellowing of colors.', '1.Fluorometholone 0.1% + Tetrahydrozoline hydrochloride 0.025% eye prep.', '1.See your eye doctor regularly.\r\n2.Eat a diet rich in beneficial nutrients.\r\n3.Quit smoking -- or better yet, never start\r\n4.Cut back on the cocktails.\r\n5.Protect those eyes from the sun.\r\n6.Keep your diabetes under control.\r\n7.Avoid using corticosteroid medications for any length of time.'),
(20, 'Color Blindness', '1.Difficulty distinguishing between colors.\r\n2.Inability to see shades or tones of the same color.\r\n3.Rapid eye movement (in rare cases).', 'Generally no cure for color blindness.', '1.To help reduce your chances of getting acquired color blindness, discuss your use of prescribed medicines with your doctor.\r\n'),
(21, 'Crossed Eyes (Strabismus)', '1.Inability to read comfortably.\r\n2.Fatigue when reading and unstable.', '1.Eye Exercise. \r\n2.Injection Clostridium botulinum toxin type A neurotoxin -> 1.25-5 units IM; <25 units per injection.', '1.There is no known way to prevent Strabismus.\r\n2.It is important to evaluate and treat Strabismus as soon as it occurs.'),
(22, 'Diabetes', '1.Urinating often.\r\n2.Feeling very thirsty.\r\n3.Feeling very hungry - even though you are eating.\r\n4.Extreme fatigue.\r\n5.Blurry vision.\r\n6.Cuts/bruises that are slow to heal.\r\n7.Weight loss - even though you are eating more (type 1).\r\n8.Tingling, pain, or numbness in the hands/feet (type 2).', '1.Diet control.\r\n2.Regular exercise. \r\n3.Insulin (human) N -> dose depends on patient\'s condition.\r\n4.Insulin (human) R -> dose depends on patient\'s condition.\r\n5.Metformin hydrochloride + pioglitazone -> dose depends on patient\'s condition. \r\n6.Glimepiride + pioglitazone -> dose depends on patient\'s condition.', '1.Check your risk of diabetes.\r\n2.Manage your weight.\r\n3.Exercise regularly.\r\n4.Eat a balanced, healthy diet.\r\n5.Limit takeaway and processed foods.\r\n6.Limit your alcohol intake.\r\n7.Quit smoking.\r\n8.Control your blood pressure.'),
(23, 'Heart Attack', '1.Discomfort, pressure, heaviness, or pain in the chest, arm, or below the breastbone.\r\n2.Discomfort radiating to the back, jaw, throat, or arm.\r\n3.Fullness, indigestion, or choking feeling (may feel like heartburn).\r\n4.Sweating, nausea, vomiting, or dizziness.\r\n5.Extreme weakness, anxiety, or shortness of breath.\r\n6.Rapid or irregular heartbeats.', 'Hospitalization.', '1.Choose a healthy eating plan such as foods low in saturated fat, trans fat, and sodium,plenty of fruits and vegetables,fiber-rich whole grains, fish ,limit sugar-sweetened beverages and red meat.\r\n2.Be physically active.\r\n3.Don’t smoke and avoid secondhand smoke.\r\n4.Know your family history.\r\n5.Tame your stress.\r\n6.Watch your weight.\r\n7.Have your blood sugar level checked.\r\n8.Don’t brush off snoring.\r\n9.Learn the warning signs of a heart attack.'),
(24, 'Brain Stroke', '1.Weakness in the arm or leg or both on the same side.\r\n2.Weakness in the muscles of the face.\r\n3.Difficulty speaking.\r\n4.Coordination problems.\r\n5.Dizziness.\r\n6.Vision problems.\r\n7.Sudden headache.\r\n8.Loss of consciousness.', 'Hospitalization.', '1.Lower blood pressure.\r\n2.Treat high cholesterol(if have) with proper diet and exercises.\r\n3.Control diabetes.\r\n4.Stop smoking.\r\n5.Eat a low-fat and low-sodium diet rich in fruits, vegetables, and fish.\r\n6.Don’t abuse alcohol or drugs..\r\n7.Lose weight.'),
(25, 'Kidney Stones', '1.Severe pain in the side and back, below the ribs.\r\n2.Pain that radiates to the lower abdomen and groin.\r\n3.Pain that comes in waves and fluctuates in intensity.\r\n4.Pain on urination.\r\n5.Pink, red or brown and cloudy or foul-smelling urine.\r\n6.Nausea and vomiting.\r\n7.Urinating more often than usual.\r\n8.Fever and chills if an infection is present.\r\n9.Urinating small amounts.', '1.Chondroitin + Glucosamine -> 1-2 tablets thrice daily.\r\n2.If needed, removal of renal stone by surgical procedure. ', '1.Stay hydrated.\r\n2.Eat more calcium-rich foods.\r\n3.Eat less sodium.\r\n4.Eat fewer oxalate-rich foods.\r\n5.Eat less animal protein.\r\n6.Avoid vitamin C supplements.\r\n7.Explore herbal remedies.\r\n'),
(26, 'Appendicites', '1.Pain around the bellybutton.\r\n2.Lower right side abdominal pain.\r\n3.Loss of appetite.\r\n4.Nausea.\r\n5.Vomiting.\r\n6.Diarrhea.\r\n7.Constipation.\r\n8.Inability to pass gas.\r\n9.Abdominal swelling.\r\n10.Low-grade fever.\r\n11.A sense that you might feel better after passing stool.', 'Surgical treatment. ', 'Unfortunately, you can’t prevent appendicitis.\r\nHowever, some effective lifestyle changes and dietary tactics may help reduce your risk for it such as :\r\n\r\n1.A high-fiber diet \r\n2.Well-balanced diet with probiotics.\r\n3.Managing your stress levels and getting enough exercise. \r\n4.Taking supplements such as beta-carotene, vitamin C and zinc.'),
(27, 'Parkinson\'s Disease', '1.Tremor/Shaking.\r\n2.Slowed movement. \r\n3.Rigid muscles.\r\n4.Impaired posture and balance.\r\n5.Loss of automatic movements.\r\n6.Speech changes.\r\n7.Writing changes.', 'Levodopa 200mg + Carbidopa 50mg + Entacapone 200mg -> one tablet/day initially; \r\ntitrate dose according to patient\'s response. \r\n', '1.Eat fresh, raw vegetables.\r\n2.Avoid pesticides and petrochemical solvents.\r\n3.Avoid excess iron.\r\n4.Avoid excess manganese.\r\n5.Consume sufficient caffeine.\r\n6.Adequate sleep/rest.\r\n7.Prevent head injuries.\r\n8.Ample exercise.\r\n'),
(28, 'Tonsilitis', '1.A very sore throat.\r\n2.Difficulty swallowing or painful swallowing.\r\n3.A scratchy-sounding voice.\r\n4.Bad breath.\r\n5.Fever.\r\n6.Chills.\r\n7.Earaches.\r\n8.Stomachaches.\r\n9.Headaches.\r\n10.A stiff neck.\r\n11.Jaw and neck tenderness due to swollen lymph nodes.\r\n12.Tonsils that appear red and swollen.\r\n13.Tonsils that have white or yellow spots.', '1.Gurgling with iodine gurgle. \r\n2.If fever & pain: paracetamol.\r\n3.Tablet Cetirizine 10mg -> one tablet at night.\r\n4.Capsule Cephradine 500mg -> one cap thrice daily for five days\r\nor Tablet Cefuroxime + Clavulanic acid -> 250mg twice daily for 5-10 days.\r\n', '1.Avoid close contact with the person suffering from Tonsillitis.\r\n2.Ask the sick person to wash their hands thoroughly and regularly; especially after using the toilet.\r\n3.Do not share a toothbrush or other personal items with the person suffering from Tonsillitis.\r\n4.Avoid sharing utensils, water bottles, glasses and food with the sick person till they are cured.\r\n5.Regularly wash and disinfect the surface and things which a suffering person comes in contact with.\r\n6.Ask the sick person to cover their moth with hands or a tissue while sneezing.\r\n7.Avoid smoking.'),
(29, 'Migraine', '1.Throbbing, pulsating pain.\r\n2.Light sensitivity.\r\n3.Sound sensitivity.\r\n4.Nausea.\r\n5.Pain on one side.\r\n6.Vision changes, blurred vision.\r\n7.Aura(flickering lights, spots, or lines).\r\n8.Vomiting.\r\n9.Depression, irritability, or excitement.', '1.Paracetamol + Caffeine...1-2 tablets 4-6 hourly; \r\nmaximum dose: 8 tablets daily.\r\n\r\n2.For prophylaxis: \r\nAmitriptyline hydrochloride(10mg) ->  10mg/day at night initially; \r\nmaintenance: 50-75mg/day at night.\r\n\r\n3.Pizotifen(0.5mg) -> 0.5mg initially; maintenance dose: 1.5mg daily as a single dose at night or in 3 divided doses.\r\n\r\n4.Propranolol(40mg) -> initially 40mg twice or thrice daily; \r\nusual range: 120-240mg/day.\r\n', '1.Track Your Triggers.\r\n2.Treat Your Allergies.\r\n3.Get Electrified.\r\n4.Stash Painkillers.\r\n5.Spit Out The Gum.\r\n6.Go Prophylactic.\r\n7.Break The Fast Every Day.\r\n8.Watch For Bolts.\r\n9.Count Your Omegas.'),
(30, 'Insomnia', '1.Fatigue.\r\n2.Problems with attention, concentration or memory (cognitive impairment).\r\n3.Poor performance at school or work.\r\n4.Moodiness or irritability.\r\n5.Daytime sleepiness.\r\n6.Impulsiveness or aggression.\r\n7.Lack of energy or motivation.\r\n8.Errors or accidents.\r\n9.Concern or frustration about your sleep.', 'Tablet Clonazepam 0.5mg at night if needed. ', '1.Stick to a regular bedtime routine.\r\n2.Eat well to sleep well.\r\n3.Cut the caffeine.\r\n4.Say yes to yoga.\r\n5.Pop some natural supplements.\r\n6.Put down the electronic gadgets.\r\n7.Embrace exercise.\r\n8.Stop smoking.'),
(31, 'Dengue Fever', '1.Sudden, high fever (up to 106 degrees Fahrenheit).\r\n2.Severe headache.\r\n3.Swollen lymph glands.\r\n4.Severe joint and muscle pains.\r\n5.Skin rash (appearing between two and five days after the initial fever).\r\n6.Mild to severe nausea.\r\n7.Mild to severe vomiting.\r\n8.Mild bleeding from the nose or gums.\r\n9.Mild bruising on the skin.\r\n10.Pain behind the eyes.', '1.Complete bed rest.\r\n2.If fever, tepid sponging;\r\nParacetamol + caffeine 1-2 tablets ->  4-6 hourly orally;\r\nParacetamol suppository per rectally if temperature > 102 degree F.\r\n3.Plenty of fluid orally. ', '1.Stay in air-conditioned or well-screened housing.\r\n2.Wear protective clothing and treat clothes with repellents like permethrin.\r\n3.Use EPA-registered mosquito repellent.\r\n4.Reduce mosquito habitat.'),
(32, 'Mumps', '1.Swollen, painful salivary glands on one or both sides of your face (parotitis).\r\n2.Fever.\r\n3.Headache.\r\n4.Muscle aches.\r\n5.Weakness and fatigue.\r\n6.Loss of appetite.\r\n7.Pain while chewing or swallowing.', '1.Complete isolated bed rest.\r\n2.For fever & pain, Ibuprofen(400-800mg) ->  8 hourly orally.\r\n3.Vaccination with MMR vaccine.', '1.Wash hands well and often with soap.\r\n2.Don\'t share eating utensils or beverage containers.\r\n3.Surfaces that are frequently touched should also be regularly cleaned with cleaning wipes.\r\n4.Limit your contact with people who have known mumps symptoms.\r\n5.Get Vaccinated.'),
(33, 'Tuberculosis', '1.Coughing that lasts three or more weeks.\r\n2.Coughing up blood.\r\n3.Chest pain, or pain with breathing or coughing.\r\n4.Unintentional weight loss.\r\n5.Fatigue.\r\n6.Fever.\r\n7.Night sweats.\r\n8.Chills.\r\n9.Loss of appetite.', 'Anticock\'s therapy (Isoniazid, rifampicin, ethambutal, pyrazinamide).', '1.Improving the ventilation in indoor spaces so there are fewer bacteria in the air.\r\n2.Using germicidal ultraviolet lamps to kill airborne bacteria in buildings \r\nwhere people at high risk of tuberculosis live or congregate.\r\n3.Treating latent infection before it becomes active.\r\n4.Taking Tuberculosis vaccine.'),
(34, 'Piles', '1.A hard lump may be felt around the anus. It consists of coagulated blood,this can be painful.\r\n2.After going to the toilet, a feeling that the bowels are still full.\r\n3.Bright red blood after a bowel movement.\r\n4.Itchiness around the anus.\r\n5.Mucus discharge when emptying the bowels.\r\n6.Pain while defecating.\r\n7.The area around the anus may be red and sore.', 'Surgical Treatment.', '1.Do not delay bowel movements.\r\n2.Use wipes over toilet paper.\r\n3.Avoid taking too long in the bathroom.\r\n4.Keep the anal area clean.\r\n5.Stay hydrated.\r\n6.Add more fiber to your diet.\r\n7.Exercise regularly.\r\n8.Lose weight if necessary.'),
(35, 'Chikungunya', '1.Symptoms usually begin 3–7 days after being bitten by an infected mosquito.\r\n2.The most common symptoms are fever and joint pain.\r\n3.Other symptoms may include headache, muscle pain, joint swelling, or rash.\r\n4.Chikungunya disease does not often result in death, but the symptoms can be severe and disabling.\r\n', '1.Complete bed rest.\r\n2.For fever & pain : \r\nTablet Paracetamol(500mg) -> orally 1-2 tablets 4-6 hourly;\r\nSuppository paracetamol if temperature > 102 degree F;\r\ntepid sponging;\r\n3.Plenty of fluid orally.', '1.Use air conditioning or window/door screens to keep mosquitoes outside. If you are not able to protect yourself from mosquitoes inside your home or hotel,\r\nsleep under a mosquito bed net.\r\n2.Help reduce the number of mosquitoes outside your home or hotel room by emptying standing water from containers such as flowerpots or buckets.\r\n3.When weather permits, wear long-sleeved shirts and long pants.\r\n4.Use insect repellents.\r\n'),
(36, 'Malaria', '1.Shaking chills that can range from moderate to severe.\r\n2.High fever.\r\n3.Profuse sweating.\r\n4.Headache.\r\n5.Nausea.\r\n6.Vomiting.\r\n7.Diarrhea.\r\n8.Anemia.\r\n9.Muscle pain.\r\n10.Convulsions.\r\n11.Bloody stools.', '1.If pain & fever :\r\nTablet paracetamol(500mg) -> 1-2 tablets 4-6 hourly orally;\r\nSuppository paracetamol if temperature >102 degree F;\r\nTepid sponging. \r\n2.Antimalarial drugs : \r\nChloroquine phosphate (250mg): 1gm (600mg base) orally stat, \r\nthen 500mg (300mg base) orally 6-8 hours later,\r\nthen 500mg (300mg base) orally at 24 hours & 48 hours after initial dose.\r\n', '1.Use air conditioning or window/door screens to keep mosquitoes outside. If you are not able to protect yourself from mosquitoes inside your home or hotel,\r\nsleep under a mosquito bed net.\r\n2.Help reduce the number of mosquitoes outside your home or hotel room by emptying standing water from containers such as flowerpots or buckets.\r\n3.When weather permits, wear long-sleeved shirts and long pants.\r\n4.Use insect repellents.\r\n'),
(37, 'Bird Flu', '1.Cough.\r\n2.Diarrhea.\r\n3.Respiratory difficulties.\r\n4.Fever (over 100.4°F or 38°C).\r\n5.Headache.\r\n6.Muscle aches.\r\n7.Malaise.\r\n8.Runny nose.\r\n9.Sore throat.\r\n', '', '1.Wash your hands regularly, particularly before and after handling food.\r\n2.Turn away from other people and cover your mouth with tissues when you cough or sneeze.\r\n3.Dispose of tissues immediately after use and wash your hands with soap and warm water.\r\n4.Avoid public places if you\'re ill. \r\n5.Make sure you maintain a good level of general health and have any recommended vaccinations, such as the pneumococcal vaccination and seasonal flu vaccine,\r\nif you\'re in a high-risk group – for example, if you have a long-term illness such as asthma or you\'re 65 or over.'),
(38, 'Anthrax', '1.A group of small blisters or bumps that may itch.\r\n2.Swelling can occur around the sore.\r\n3.A painless skin sore (ulcer) with a black center that appears after the small blisters or bumps.\r\n4.Most often the sore will be on the face, neck, arms, or hands.\r\n', '1.Doxycycline 100mg -> one capsule twice daily for 60 days.', '1.Do not eat meat that has not been properly slaughtered and cooked.\r\n2.Do not work with raw animal hides, fur or skin, especially those of goats, sheep, or cows.\r\n'),
(39, 'Polio', '1.Fever.\r\n2.Sore throat.\r\n3.Headache.\r\n4.Vomiting.\r\n5.Fatigue.\r\n6.Back pain or stiffness.\r\n7.Neck pain or stiffness.\r\n8.Pain or stiffness in the arms or legs.\r\n9.Muscle weakness or tenderness.\r\n10.Meningitis.', 'Because no cure for polio exists, the focus is on increasing comfort, speeding recovery and preventing complications. Supportive treatments include:\r\n\r\n1.Bed rest.\r\n2.Pain relievers.\r\n3.Portable ventilators to assist breathing.\r\n4.Moderate exercise (physical therapy) to prevent deformity and loss of muscle function.\r\n5.A nutritious diet.', '1.Polio can be prevented through immunization. Polio vaccine, given multiple times, almost always protects a child for life.'),
(40, 'Diptheria', '1.A thick, gray membrane covering your throat and tonsils.\r\n2.A sore throat and hoarseness.\r\n3.Swollen glands (enlarged lymph nodes) in your neck.\r\n4.Difficulty breathing or rapid breathing.\r\n5.Nasal discharge.\r\n6.Fever and chills.\r\n7.Malaise.', '1.Isolated bed rest.\r\n2.Injection Benzathine penicillin/Benzyl penicillin.\r\n3.Vaccination with DT or DPT vaccine.', '1.The best way to prevent diphtheria is to get vaccinated. \r\n2.Hygienic Lifestyle.'),
(41, 'Tetanus', '1.Stiffness of the neck, jaw, and other muscles, often accompanied by a grotesque, grinning expression.\r\n2.Difficulty swallowing.\r\n3.Irritability.\r\n4.Uncontrollable spasms of the jaw, called lockjaw, and neck muscles.\r\n5.Painful, involuntary contraction of other muscles.\r\n', '', '1.Get vaccinated. \r\n2.Hygienic Lifestyle.'),
(42, 'Typhoid ', '1.Poor appetite.\r\n2.Abdominal pain.\r\n3.Headaches.\r\n4.Generalized aches and pains.\r\n5.Fever, often up to 104 F.\r\n6.Lethargy (usually only if untreated).\r\n7.Intestinal bleeding or perforation (after two to three weeks of the disease).\r\n8.Diarrhea or constipation.', '', '1.Wash your hands.\r\n2.Avoid drinking untreated water.\r\n3.Avoid raw fruits and vegetables.\r\n'),
(43, 'Meningitis', '1.Fever, cold hands and feet.\r\n2.Vomiting.\r\n3.Drowsy, difficult to wake.\r\n4.Confusion and irritability.\r\n5.Severe muscle pain.\r\n6.Pale, blotchy skin. Spots/rash. See the Glass Test.\r\n7.Severe headache.\r\n8.Stiff neck.\r\n9.Dislike bright lights\r\n10.Convulsions/seizures', '1.Hospitalization.\r\n2.Injection Ceftriaxone -> 2gm IV 12 hourly for 7-14 days.', '1.Getting adequate amounts of rest.\r\n2.Not smoking.\r\n3.Avoiding contact with sick people.'),
(44, 'Asthma', '1.Shortness of breath.\r\n2.Chest tightness or pain.\r\n3.Trouble sleeping caused by shortness of breath, coughing or wheezing.\r\n4.A whistling or wheezing sound when exhaling (wheezing is a common sign of asthma in children).\r\n5.Coughing or wheezing attacks that are worsened by a respiratory virus, such as a cold or the flu.', '', '1.Get vaccinated for influenza and pneumonia. \r\n2.Fully take part in exercise and sports.\r\n3.Sleep all night.\r\n4.Attend school or work regularly.\r\n5.Have the clearest lungs possible.\r\n6.Have no emergency visits or stays in the hospital.'),
(45, 'Ebola', '1.Fever.\r\n2.Severe headache.\r\n3.Joint and muscle aches.\r\n4.Chills.\r\n5.Weakness.', '', '1.There’s no vaccine to prevent Ebola. The best way to avoid catching the disease is by not traveling to areas where the virus is found.\r\n2.Health care workers can prevent infection by wearing masks, gloves, and goggles whenever they come into contact with people who may have Ebola.\r\n'),
(46, 'Arthitis', '1.Fatigue.\r\n2.Joint pain.\r\n3.Joint tenderness.\r\n4.Joint swelling.\r\n5.Joint redness.\r\n6.Joint warmth.\r\n7.Joint stiffness.\r\n8.Loss of joint range of motion.\r\n9.Many joints affected (polyarthritis).\r\n10.Limping.\r\n11.Joint deformity.\r\n12.Both sides of the body affected (symmetric).\r\n13.Loss of joint function.\r\n14.Anemia.\r\n15.Fever.', '', '1.Eat fish.\r\n2.Control your weight.\r\n3.exercise.\r\n4.Avoid injury.\r\n5.Protect your joints.'),
(47, 'Bronchitis', '1.Cough.\r\n2.Production of mucus (sputum), which can be clear, white, yellowish-gray or green in color — rarely, it may be streaked with blood.\r\n3.Fatigue.\r\n4.Shortness of breath.\r\n5.Slight fever and chills.\r\n6.Chest discomfort.\r\n', '', '1.Do not start smoking; quit smoking if you already smoke.\r\n2.Avoid lung irritants such as smoke, dust, fumes, vapors, and air pollution. If avoiding exposure is not possible, wear a mask that covers the nose and mouth.\r\n3.Wash hands often to limit exposure to germs and bacteria.\r\n4.Get a yearly flu vaccine.\r\n5.Get a pneumonia vaccine.'),
(48, 'Ear Infection(Ottitis Media)', '1.Mild pain or discomfort inside the ear.\r\n2.A feeling of pressure inside the ear that persists.\r\n3.Fussiness in young infants.\r\n4.Pus-like ear drainage.\r\n5.Hearing loss.', '1.For pain & fever : \r\nParacetamol + Caffeine -> 1-2 tablets 4-6 hourly.\r\n2.Capule Cephradine 500mg -> one capsule 8 hourly for 7 days.\r\n3.Tablet Cetirizine 10mg -> one tablet at night.\r\n4.Ciprofloxacin 0.3% / Lomefloxacin 0.3% ear drop -> two drops instilled into affected ear for 7 days.\r\n', '1.Create smoke-free environment.\r\n2.Minimal usage of pacifiers.\r\n3.Get pneumococcal vaccination.\r\n4.Get flu vaccinations.\r\n5.Have xylitol gum.\r\n6.Dietary supplements of zinc.\r\n7.Tonsil surgery and the use of ear tubes.'),
(49, 'Influenza', '1.Fever or feeling feverish/chills.\r\n2.Cough.\r\n3.Sore throat.\r\n4.Runny or stuffy nose.\r\n5.Muscle or body aches.\r\n6.Headaches.\r\n7.Fatigue (tiredness).\r\n8.Some people may have vomiting and diarrhea, though this is more common in children than adults.\r\n', '1.Paracetamol + Caffeine for subsiding fever & pain -> 1-2 tablets 4-6 hourly.\r\n2.Capsule Amantadine hydrochloride (100mg) -> one capsule daily for 5 days.\r\n', '1.Don\'t smoke.\r\n2.Wash your hands often. \r\n3.Breast-feeding infants for the first year of life.\r\n4.Practicing good hygiene, including washing hands regularly.\r\n');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
